server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: api-runner
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/api-runner
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: run-app
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug
    root: info

springdoc:
  packages-to-scan: com.mavassoler.runner.runner